import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../globals.css";
import Header from "@/components/headers/header";

const lato = Lato({ subsets: ["latin"], weight: ['400','700'] });

export const metadata: Metadata = {
  title: "LinkList App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main>
        <Header />
        <div className="max-w-4xl mx-auto p-6">
        {children}
        </div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
